import { Regioni } from './regioni';

export const COORDS: Regioni[]=[
    {  
        name: "Abruzzo",
        lat: 42.4576220,
        lng: 13.9274753,
        capoluoghi: ["Chieti", "L'Aquila", "Pescara", "Teramo"],
        province: ["CH", "AQ", "PE", "TE"],
        capitale:["L'Aquila"],
        piatto: ["Arrosticini di Pecora"],
        escursioni: ["Gran Sasso"],
        descrizione: ["L'Abruzzo è una regione italiana che si trova a est di Roma, tra l'Adriatico e gli Appennini. L'entroterra è costituito per la gran parte da parchi nazionali e riserve naturali. La regione comprende anche paesini medievali e rinascimentali abbarbicati sulle colline. Il capoluogo di regione, L'Aquila, è una città cinta da mura, danneggiata dal terremoto del 2009. La Costa dei Trabocchi, con calette di sabbia, prende il nome dai tradizionali pontili per la pesca."],
        img: ["../assets/immagini ragioni/Abruzzo/Schermata 2020-01-22 alle 14.21.08.png","../assets/immagini ragioni/Abruzzo/abruzzo.jpg"],
    },
    {   name: "Basilicata",
        lat: 39.9567890,
        lng: 16.5060872,
        capoluoghi: ["Matera", "Potenza"],
        province: ["MT", "PZ"],
        capitale:["Matera"],
        piatto: ["Pane di Matera"],
        escursioni: ["Sassi di Matera"],
        descrizione: ["La Basilicata, in passato Lucania, è una regione italiana a statuto ordinario dell'Italia meridionale di 562 869 abitanti con capoluogo Matera. Comprende la provincia di Potenza e la provincia di Matera. Altri centri principali, oltre ai due capoluoghi Potenza e Matera, sono Policoro, Melfi e Pisticci."],
        img: ["../assets/immagini ragioni/Basilicata/Schermata 2020-01-22 alle 14.59.00.png", "../assets/immagini ragioni/Basilicata/matera.jpg"],
    },

    {   name: "Calabria",
        lat: 38.9092915,
        lng: 16.6439327,
        capoluoghi: ["Catanzaro", "Cosenza", "Crotone", "Reggio Calabria", "Vibo Valentia"],
        province: ["CZ", "CS", "KR", "RC", "VV"],
        capitale:["Reggio Calabria"],
        piatto: ["Filei alla 'nduja"],
        escursioni: ["Il Castello Ducale di Corigliano Calabro"],
        descrizione: ["Situata nella zona sud-occidentale dell'Italia, la Calabria occupa la 'punta' dello stivale. È una regione bruciata dal sole con aspre montagne, paesini antichi e una spettacolare costa con molte spiagge rinomate. La città più grande è Reggio Calabria, sulla costa, dove si trovano il Museo Archeologico Nazionale e i Bronzi di Riace, due famosi guerrieri greci del V secolo a.C."],
        img: ["../assets/immagini ragioni/Calabria/Schermata 2020-01-22 alle 14.19.49.png", "../assets/immagini ragioni/Calabria/2430_n_Calabria_estiva.jpg"],

    },
    {   name: "Campania",
        lat: 40.8399968,
        lng: 14.2528707,
        capoluoghi: ["Avellino", "Benevento", "Caserta", "Napoli", "Salerno"],
        province: ["AV", "BN", "CE", "NA", "SA"],
        capitale:["Napoli"],
        piatto: ["Pizza"],
        escursioni: ["Reggia di Caserta"],
        descrizione: ["La Campania è una regione del sud-ovest dell'Italia conosciuta per le rovine antiche e la spettacolare costiera. Napoli, il capoluogo di regione, è una città molto animata circondata da un ambiente naturale straordinario, con il famoso Monte Vesuvio grigio a forma di cono e le profonde acque blu del Golfo di Napoli. A sud, nella Costiera Amalfitana, si trovano cittadine colorate a tinte pastello come Positano, Amalfi e Ravello, incastonate tra le rocce e il mare."],
        img: ["../assets/immagini ragioni/Campania/Schermata 2020-01-23 alle 12.10.18.png", "../assets/immagini ragioni/Campania/2018-01-05.jpg"],
    },
    {   name: "Emilia-Romagna",
        lat: 44.4944456,
        lng: 11.0492311,
        capoluoghi: ["Bologna", "Ferrara", "Forlì-Cesena", "Modena", "Parma", "Piacenza", "Ravenna", "Reggio Emilia", "Rimini"],
        province: ["BO", "FE", "FC", "MO", "PR", "PC", "RA", "RE", "RN"],
        capitale:["Bologna"],
        piatto: ["Tortelli"],
        escursioni: ["Tomba di Dante e Quadrarco di Braccioforte"],
        descrizione: ["L’Emilia-Romagna è una regione del nord Italia, che si estende dagli Appennini fino al fiume Po, a nord. La regione è conosciuta per le città medievali, la ricca gastronomia e le località balneari. Il capoluogo, Bologna, è una città vivace, sede dell'università risalente all'XI secolo, caratterizzata dai portici lungo strade e piazze del centro medievale. Ravenna, sulla costa adriatica, è famosa per i suoi mosaici bizantini dai colori vivaci."],
        img:["../assets/immagini ragioni/Emilia Romagna/Schermata 2020-01-22 alle 14.33.54.png", "../assets/immagini ragioni/Emilia Romagna/2019-12-15.jpg"]
    },    
    {   name: "Friuli-Venezia-Giulia",
        lat: 45.6536295,
        lng: 13.3784072,
        capoluoghi: ["Gorizia", "Pordenone", "Trieste", "Udine"],
        province: ["GO", "PN", "TS", "UD"],
        capitale:["Trieste"],
        piatto: ["Frico con le patate"],
        escursioni: ["Castello di Miramare"],
        descrizione: ["Il Friuli Venezia Giulia è una regione del nord-est dell'Italia che si affaccia sul mare Adriatico e confina con l'Austria e la Slovenia. La regione ospita i picchi delle Dolomiti e i vigneti famosi per i vini bianchi. Trieste, il capoluogo, apparteneva in passato all’Impero austro-ungarico del XIX secolo. Le attrazioni più famose sono il centro storico, il lungomare di piazza dell'Unità d'Italia e il Castello di Miramare, una ex residenza reale."],
        img:["../assets/immagini ragioni/Friuli/Schermata 2020-01-22 alle 14.35.38.png", "../assets/immagini ragioni/Friuli/2019-11-16.jpg"]
    },
    {   name: "Lazio",
        lat: 41.8954656,
        lng: 12.4823243,
        capoluoghi: ["Frosinone", "Latina", "Rieti", "Roma", "Viterbo"],
        province: ["FR", "LT", "RI", "RM", "VT"],
        capitale:["Roma"],
        piatto: ["Pasta alla carbonara"],
        escursioni: ["Colosseo"],
        descrizione: ["Il Lazio è una regione dell'Italia centrale affacciata sul Mar Tirreno. Il suo capoluogo, Roma, è capitale d'Italia ed è stato il cuore dell'antico Impero romano. Tra i suoi monumenti iconici si annovera il Colosseo, un anfiteatro che poteva ospitare migliaia di spettatori. Sulla costa, l'antico porto di Ostia conserva ancora raffinati mosaici e un teatro. Nell'entroterra si trovano le boscose montagne degli Appennini, con riserve naturali, laghi e paesini in pietra."],
        img:["../assets/immagini ragioni/Lazio/Schermata 2020-01-22 alle 14.29.05.png", "../assets/immagini ragioni/Lazio/colosseo.jpg"]
    },
    {   name: "Liguria",
        lat: 44.4070624,
        lng: 8.9339889,
        capoluoghi: ["Genova", "Imperia", "La Spezia", "Savona"],
        province: ["GE", "IM", "SP", "SV"],
        capitale:["Genova"],
        piatto: ["Trofie con pesto genovese"],
        escursioni: ["Acquario di Genova"],
        descrizione: ["La Liguria è una regione a forma di mezzaluna nell'Italia nord-occidentale. La sua costa mediterranea è nota come Riviera ligure. I 5 vivaci villaggi di pescatori delle Cinque Terre, così come le eleganti Portofino e Santa Margherita Ligure, si trovano sulla costa orientale o Riviera di Levante. La costa occidentale, la Riviera di Ponente, ospita Sanremo, una località antica con un casinò di inizio '900 e un lungomare fiorito."],
        img:["../assets/immagini ragioni/liguria/Schermata 2020-01-22 alle 14.37.19.png", "../assets/immagini ragioni/liguria/2018-02-10.jpg"]
    },
    {   name: "Lombardia",
        lat: 45.4036707,
        lng: 9.8881263,
        capoluoghi: ["Bergamo", "Brescia", "Como", "Cremona", "Lecco", "Lodi", "Mantova", "Milano", "Monza e Brianza", "Pavia", "Sondrio", "Varese"],
        province: ["BG", "BS", "CO", "CR", "LC", "LO", "MN", "MI", "MB", "PV", "SO", "VA"],
        capitale:["Milano"],
        piatto: ["Risotto alla milanese"],
        escursioni: ["Lago di Como"],
        descrizione: ["La Lombardia è una regione dell'Italia Settentrionale. Il suo capoluogo, Milano, è un centro mondiale della moda e della finanza, con molti negozi e ristoranti di lusso. Il Duomo in stile gotico e la chiesa di Santa Maria delle Grazie, che ospita il dipinto 'L'Ultima Cena di Leonardo da Vinci', testimoniano secoli di arte e cultura. A nord di Milano, il lago di Como è un elegante località prealpina con uno straordinario panorama."],
        img:["../assets/immagini ragioni/Lombardia/Schermata 2020-01-22 alle 14.37.55.png", "../assets/immagini ragioni/Lombardia/2019-09-04.jpg"]
    },
    {   name: "Marche",
        lat: 43.2158281,
        lng: 13.3189447,
        capoluoghi: ["Ancona", "Ascoli Piceno", "Fermo", "Macerata", "Pesaro e Urbino"],
        province: ["AN", "AP", "FM", "MC", "PU"],
        capitale:["Ancona"],
        piatto: ["Olive all'ascolana"],
        escursioni: ["Grotte di Frasassi"],
        descrizione: ["Le Marche, regione dell'Italia orientale, sorgono tra le montagne degli Appennini e il Mare Adriatico. Il capoluogo, Ancona, è una città portuale sulla Riviera del Conero, una zona caratterizzata da insenature sabbiose, scogliere calcaree e paesini medievali. Pesaro invece è la città natale del celebre compositore Rossini. Nell'entroterra si trovano antiche fortificazioni in cima alle colline e le valli glaciali del Parco Nazionale dei Monti Sibillini."],
        img:["../assets/immagini ragioni/marche/Schermata 2020-01-22 alle 14.23.33.png","../assets/immagini ragioni/marche/mondavio-il-borgo-delle-marche-dominato-dalla-rocca.jpg"]
    },
    {   name: "Molise",
        lat: 41.5600859,
        lng: 14.9047992,
        capoluoghi: ["Campobasso", "Isernia"],
        province: ["CB", "IS"],
        capitale:["Campobasso"],
        piatto: ["Cavatelli"],
        escursioni:["Santuario Santa Maria Assunta"],
        descrizione: ["Il Molise è una regione montuosa italiana con un tratto di costa che si affaccia sul Mar Adriatico. Include una parte del Parco nazionale d'Abruzzo nella Catena montuosa dell'Appennino, con una ricca fauna selvatica e sentieri. Il capoluogo regionale, Campobasso, è noto per il Castello Monforte, situato su un monte, e per le chiese romaniche. A nord si trova l'area archeologica di Pietrabbondante con un antico teatro e un tempio sannita."],
        img:["../assets/immagini ragioni/Molise/Schermata 2020-01-22 alle 14.38.46.png", "../assets/immagini ragioni/Molise/IMG_7074-e1538391083709.jpg"]
        
    },
    {   name: "Piemonte",
        lat: 45.0706029,
        lng: 8.0067102,
        capoluoghi: ["Alessandria", "Asti", "Biella", "Cuneo", "Novara", "Torino", "Verbano Cusio Ossola", "Vercelli"],
        province: ["AL", "AT", "BI", "CN", "NO", "TO", "VB", "VC"],
        capitale:["Torino"],
        piatto: ["Bagna Cauda"],
        escursioni: ["Mole Antonelliana"],
        descrizione: ["Il Piemonte è una regione italiana che confina con la Francia e la Svizzera, situata ai piedi delle Alpi. È conosciuta per la cucina raffinata e per i vini, come il Barolo. Il capoluogo è Torino, che offre numerosi esempi di architettura barocca e ospita la celebre Mole Antonelliana, con la sua guglia altissima. Il Museo dell'Automobile di Torino è dedicato alla principale attività industriale della città, mentre il Museo Egizio espone collezioni archeologiche e antropologiche."],
        img:["../assets/immagini ragioni/Piemonte/Schermata 2020-01-22 alle 14.40.20.png","../assets/immagini ragioni/Piemonte/questamamett.jpg"],
        
    },
    {   name: "Puglia",
        lat: 40.1260529,
        lng: 17.8692905,
        capoluoghi: ["Bari", "Barletta-Andria-Trani", "Brindisi", "Lecce", "Foggia", "Taranto"],
        province: ["BA", "BT", "BR", "LE", "FG", "TA"],
        capitale:["Bari"],
        piatto: ["Orecchiette alle cime di rapa"],
        escursioni:["Trulli di Alberobello"],
        descrizione: ["La Puglia è una regione meridionale che forma il 'tacco' dello stivale italiano. È famosa per i villaggi collinari dal caratteristico intonaco bianco, per la campagna dal sapore antico e per le centinaia di chilometri di costa mediterranea. Il capoluogo, Bari, è una vivace città portuale e universitaria, mentre Lecce è conosciuta come la 'Firenze del Sud' per via della sua architettura barocca. Alberobello e la Valle d'Itria sono invece la patria dei trulli, i tradizionali edifici di pietra dal caratteristico tetto conico."],
        img:["../assets/immagini ragioni/Puglia/Schermata 2020-01-22 alle 14.41.34.png","../assets/immagini ragioni/Puglia/2020-01-12.jpg"]
    },
    {   name: "Sardegna",
        lat: 39.7149029,
        lng: 9.1094988,
        capoluoghi: ["Cagliari", "Carbonia-Iglesias", "Medio Campidano", "Nuoro", "Ogliastra", "Olbia-Tempio", "Oristano", "Sassari"],
        province: ["CA", "CI", "VS", "NU", "OG", "OT", "OR", "SS"],
        capitale:["Cagliari"],
        piatto: ["Porceddu"],
        escursioni:["Cattedrale di Santa Maria"],
        descrizione: ["La Sardegna è una grande isola italiana situata nel Mar Mediterraneo e caratterizzata da circa 2000 km di costa, spiagge sabbiose e da un entroterra montuoso attraversato da sentieri escursionistici. Il suo paesaggio frastagliato è costellato da migliaia di nuraghi, misteriose rovine in pietra dalla forma ad alveare, costruiti nell'Età del Bronzo. Uno dei nuraghi più grandi e più antichi è il Su Nuraxi di Barumini, che risale al 1500 a.C."],
        img:["../assets/immagini ragioni/Sardegna/Schermata 2020-01-22 alle 14.44.26.png","../assets/immagini ragioni/Sardegna/chess.jpg"]
    },
    {   name: "Sicilia",
        lat: 37.5111111,
        lng: 14.0612966,
        capoluoghi: ["Agrigento", "Caltanissetta", "Catania", "Enna", "Messina", "Palermo", "Ragusa", "Siracusa", "Trapani"],
        province: ["AG", "CL", "CT", "EN", "ME", "PA", "RG", "SR", "TP"],
        capitale:["Palermo"],
        piatto: ["Arancini"],
        escursioni: ["Tempio della Concordia Agrigento"],
        descrizione: ["La Sicilia è l'isola più grande del mar Mediterraneo. Si affaccia a nord sul mar Tirreno, a nord-est è divisa dalla penisola dallo stretto di Messina ed è bagnata a est dal mar Ionio, a sud-ovest è divisa dall'Africa dal canale di Sicilia. L'isola ha una forma che ricorda approssimativamente quella di un triangolo."],
        img:["../assets/immagini ragioni/sicilia/Schermata 2020-01-22 alle 14.43.05.png","../assets/immagini ragioni/sicilia/IMG_20170709_125603-EFFECTS.jpg"]
    },
    {   name: "Toscana",
        lat: 43.0687324,
        lng: 11.0000013,
        capoluoghi: ["Arezzo", "Firenze", "Grosseto", "Livorno", "Lucca", "Massa e Carrara", "Pisa", "Pistoia", "Prato", "Siena"],
        province: ["AR", "FI", "GR", "LI", "LU", "MS", "PI", "PT", "PO", "SI"],
        capitale:["Firenze"],
        piatto: ["La Fiorentina"],
        escursioni:["Torre di Pisa"],
        descrizione: ["La Toscana è una regione dell'Italia centrale. Il suo capoluogo, Firenze, ospita alcune tra le opere di arte e architettura rinascimentale più famose al mondo, come il David di Michelangelo, le opere di Botticelli alla Galleria degli Uffizi e il Duomo. Il territorio della regione è variegato, e comprende gli aspri Appennini, le spiagge dell'isola d'Elba nel mar Tirreno, gli oliveti e i vigneti del Chianti."],
        img:["../assets/immagini ragioni/toscana/Schermata 2020-01-22 alle 14.45.58.png","../assets/immagini ragioni/toscana/IMG_20191222_135106.jpg"]
    },
    {   name: "Trentino-Alto-Adige",
        lat: 45.8702531,
        lng: 11.1216386,
        capoluoghi: ["Bolzano", "Trento"],
        province: ["BZ", "TN"],
        capitale:["Trento"],
        piatto: ["Canederli"],
        escursioni: ["Sacrario Militare del Leiten"],
        descrizione: ["Il Trentino-Alto Adige è una regione dell'Italia Settentrionale che confina con la Svizzera e l'Austria. È nota per i castelli medievali, come Castel Tirolo, Castel Roncolo e Castel d'Appiano. La regione comprende parte delle Dolomiti, una sezione delle Alpi italiane conosciuta per le cime dentellate in pietra calcarea. Trento, il capoluogo della regione, ospita palazzi rinascimentali con facciate affrescate e il Castello del Buonconsiglio, sede di collezioni d'arte."],
        img:["../assets/immagini ragioni/trentino/Schermata 2020-01-22 alle 14.56.38.png", "../assets/immagini ragioni/trentino/trentino.jpeg"]
    },
    {   name: "Umbria",
        lat: 43.1107009,
        lng: 12.0091720,
        capoluoghi: ["Perugia", "Terni"],
        province: ["PG", "TR"],
        capitale:["Perugia"],
        piatto: ["Pasta alla Norcina"],
        escursioni:["Basilica di San Francesco "],
        descrizione: ["L'Umbria, che confina con Toscana, Lazio e Marche, viene anche chiamata 'il cuore verde d'Italia'; è conosciuta per le città medievali in cima alle colline, i folti boschi e la cucina, in particolare i tartufi e il vino. Il capoluogo di regione, Perugia, sorge tra le colline e ospita il Palazzo dei Priori, sede della Galleria nazionale dell'Umbria. Il cuore pulsante della città è il pedonale corso Vannucci."],
        img:["../assets/immagini ragioni/umbria/Schermata 2020-01-22 alle 14.48.28.png", "../assets/immagini ragioni/umbria/DSCF2335.JPG"]
    },
    {   name: "Valle-d'Aosta",
        lat: 45.7356745,
        lng: 8.30000097,
        capoluoghi: ["Aosta"],
        province: ["AO"]  ,          
        capitale:["Aosta"],
        piatto: ["Polenta Concia"],
        escursioni:["Arco d'Augusto"],
        descrizione: ["La Valle d'Aosta è una regione del nord-ovest dell'Italia al confine con Francia e Svizzera. Situata sulle Alpi occidentali, è nota per i picchi innevati del Cervino, del Monte Bianco, del Monte Rosa e del Gran Paradiso. Courmayeur e Cervinia sono tra i resort sciistici più importanti. La campagna della regione è disseminata di castelli e fortezze medievali, come il Castello di Fénis e il Castello di Verrès, risalenti al XIV secolo."],
        img:["../assets/immagini ragioni/Valle d'aosta/Schermata 2020-01-22 alle 14.49.17.png","../assets/immagini ragioni/Valle d'aosta/PICT_20150506_143103.JPG"]
    },
    {   name: "Veneto",
        lat: 45.4343363,
        lng: 12.1387844,
        capoluoghi: ["Belluno", "Padova", "Rovigo", "Treviso", "Venezia", "Verona", "Vicenza"],
        province: ["BL", "PD", "RO", "TV", "VE", "VR", "VI"],
        capitale:["Venezia"],
        piatto: ["Risi e Bisi"],
        escursioni: ["Basilica di San Marco"],
        descrizione: ["Il Veneto è una regione del nord-est dell'Italia che si estende dalle Dolomiti al mar Adriatico. Venezia, il capoluogo, è famosa per i canali, l'architettura gotica e il carnevale. Per più di un millennio, tra i secoli VII e XVIII, il Veneto fece parte della potente Repubblica di Venezia. Vicino al Lago di Garda, un lago che bagna le Alpi, sorge Verona, la città medievale dove Shakespeare ambientò 'Giulietta e Romeo'."],
        img:["../assets/immagini ragioni/veneto/Schermata 2020-01-22 alle 14.30.00.png","../assets/immagini ragioni/veneto/2019-09-18.jpg"]
    }
]